baseURL = "https://gguilt.com"
languageCode = "en-us"
title = "gguilt"
theme = "smol"
FootnoteReturnLinkContents = "↩"

[permalinks]
	posts = "/:year/:month/:title/"
	
# Parameters
[params]
	subtitle = "Memento mori, memento vivere."
	dateFmt = "2006-01-02 15:04 Monday"
	copyStart = "2019"

# Header
[menu]
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		url = "/posts/"
		weight = 1
	[[menu.main]]
		identifier = "tags"
		name = "Tags"
		url = "/tags/"
		weight = 2
	[[menu.main]]
		identifier = "categories"
		name = "Categories"
		url = "/categories/"
		weight = 3

# Footer
[[menu.footer]]
	name = "Github"
	url = "https://github.com/gguilt"
	weight = 1
[[menu.footer]]
	name = "GitLab"
	url = "https://gitlab.com/gguilt"
	weight = 2