baseURL = "https://blog.gguilt.com"
languageCode = "en-us"
title = "gguilt"
theme = "kat"
FootnoteReturnLinkContents = "↩"

[permalinks]
	posts = "/:year/:month/:title/"

# Languages
defaultContentLanguage = 'en'
[languages]
  [languages.en]
	subtitle = "Meditations"
    weight = 1
  [languages.de]
	subtitle = "Mein blog"
    weight = 2
  [languages.tr]
	subtitle = "Kendime düşünceler"
    weight = 3

# Parameters
[params]
	subtitle = "Meditations"
	dateFmt = "2006-01-02 15:04 Monday"
	copyStart = "2019"

	[params.navigation]
    	help = 'Help'

# Header
[menu]
	[[menu.main]]
		identifier = "posts"
		name = "Posts"
		url = "/posts/"
		weight = 1
	[[menu.main]]
		identifier = "tags"
		name = "Tags"
		url = "/tags/"
		weight = 2
	[[menu.main]]
		identifier = "categories"
		name = "Categories"
		url = "/categories/"
		weight = 3

# Footer
[[menu.footer]]
	name = "Github"
	url = "https://github.com/gguilt"
	weight = 1
[[menu.footer]]
	name = "GitLab"
	url = "https://gitlab.com/gguilt"
	weight = 2
